### ISSUE TITLE
classifier = Model.load_classifier('grayscale_classifier.h5')

### ISSUE THREAD

**Issue by UlisesMiranda** [Mohamedyasserhelmy/Sign-Language-Translator-ASL-#4]
Hey, hi!!.
I´ve seen your proyect i would like to check it, but i have trouble with this line "classifier = Model.load_classifier('grayscale_classifier.h5')" in handDetector.py", could explain to me where do i get this greyscale_classifier?

**Comment by mgblaylo** [comment]
I have the same problem

**Comment by Mohamedyasserhelmy** [comment]
You can download grayscale classifier from the following link :  
[](https://www.mediafire.com/file/n84dxrqw0sv4ga7/grayscale_classifier.h5/file?fbclid=IwAR2qcwE5npqKVwW6G30g8Sw0Nm8x8boLt7P3-DLcLPK284sMk_AJ1WvTzB4)
Please leave a star and share the project widely
