### ISSUE TITLE
No file or directory found at grayscale_classifier.h5

### ISSUE THREAD

**Issue by ghost** [Mohamedyasserhelmy/Sign-Language-Translator-ASL-#5]
error at line 15, handDetector.py.
where can i find the model training link of google colab

**Comment by Mohamedyasserhelmy** [comment]
You can Download The Classifier from this link and don't forget to add star  : 
https://www.mediafire.com/file/n84dxrqw0sv4ga7/grayscale_classifier.h5/file?fbclid=IwAR1EonfpRChZEK1GhsW6vxTWQG7iTLeoiMislnhbJ3Bto_id7PunLmLtWdE

**Comment by Mohamed007k** [comment]
the file is not found in the link
